apiVersion: v1
kind: Secret
metadata:
  name: seldon-init-container-secret
type: Opaque
stringData:
  RCLONE_CONFIG_S3_TYPE: s3
  RCLONE_CONFIG_S3_PROVIDER: minio
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: FABZ5wWZJD7dPekP
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: 9EbUHvsgVlf8NSQ8Rjp49cyQerBpR3iu
  RCLONE_CONFIG_S3_ENDPOINT: http://minio-ops-spamdetector-hl.minio.svc.cluster.local:9000
  RCLONE_CONFIG_S3_ENV_AUTH: "false"
