name: Model API Dockerize
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: actions/checkout@v3
      - name: Build the Docker Image
        run: docker build -t spamdetector-modelapi ModelAPI/
