name: Model API Dockerize Publish
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        env:
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      - name: Docker Image Build
        run: docker build -t mcandemir/spamdetector-modelapi:$(date +%s) ModelAPI/
      - name: Docker Push
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/ops-spamdetector:spamdetector-modelapi ModelAPI/
