name: Web API Dockerize
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t spamdetector-webapi WebAPI/
