name: Web API Dockerize Publish
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        env:
          DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
        run: |
          docker login -u mcandemir -p $DOCKERHUB_TOKEN
      - name: Docker Image Build
        run: docker build -t mcandemir/spamdetector-webapi:v1.0.0 WebAPI/
      - name: Docker Push
        run: docker push mcandemir/spamdetector-webapi:v1.0.0
